### ISSUE TITLE
[Bug]: The CSS of the new quote modal .  

### ISSUE THREAD

**Issue by SaraswatGit** [SaraswatGit/PlanZap#238]
### Contact Details

saraswatmajumder@gmail.com

### What happened?

![image](https://user-images.githubusercontent.com/58114914/159735693-d5207d5f-9867-412c-93a2-f3aaca3a5bf1.png)
The CSS seems messed up 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KushalGhosh9899** [comment]
Kindly assign this issue to me

**Comment by SaraswatGit** [comment]
@KushalGhosh9899  The input box is too small , u can make in longer , remove border(except bottom) and white background

**Comment by Sukriti-m** [comment]
Hi @SaraswatGit 
If this task is being delayed, then I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC'22.

**Comment by KushalGhosh9899** [comment]
Hey @Sukriti-m , glad to hear that you are very interested to solve this issue but this issue was on hold due to bug #243, now this bug is solved so I don't think resolving these issues will take much time.
I highly recommend you please look for other issues to solve or else you can wait 1 or 2 days after that you can start working on this issue as well.
Thank you

**Comment by SMD-1** [comment]
can i work on this issue
